Repository TheCodingBlogs/Resource-CSE-Books, pull requests merged in 2022-10, with the labels that each got.

#5 Create readme.md
  07.  Java books/readme.md
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#4 added android folder
  06. Android dev books/readme.md
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#3 Create readme.md
  05. Hacking Books/readme.md
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#1 Created readme.md
  03. Web development books/readme.md
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#2 Create readme.md
  04. Programming Books/readme.md
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#6 Create readme.md
  08. python books/readme.md
Labels: hacktoberfest-accepted, hacktoberfest

#9 python1
  02. Dsa books/thinkpython2 (1).pdf
Labels: hacktoberfest-accepted, hacktoberfest

#10 Add files via upload
  06. Android dev books/KotlinNotesForProfessionals.pdf
Labels: hacktoberfest-accepted, hacktoberfest

#11 Add files via upload
  05. Hacking Books/LinuxNotesForProfessionals.pdf
Labels: hacktoberfest-accepted, hacktoberfest

#14 c notes for pro
  01. Cpp Books/CNotesForProfessionals.pdf
Labels: hacktoberfest-accepted, hacktoberfest

#15 Py
  03. Web development books/ReactNativeNotesForProfessionals.pdf
  08. python books/GitNotesForProfessionals.pdf
Labels: hacktoberfest-accepted, hacktoberfest

#19 Add files via upload
  4.LECTURE 3-STRUCTURE n UNION.ppt
Labels: hacktoberfest-accepted, hacktoberfest

#20 Add files via upload
  5.LECTURE 4-5-FUNCTIONS(COMPLETE).ppt
Labels: hacktoberfest-accepted, hacktoberfest

#21 Add files via upload
  9.LECTURE 11-CLASSES.ppt
Labels: hacktoberfest-accepted, hacktoberfest

#22 Add files via upload
  LECTURE-24-Modes of Inheritance.ppt
Labels: hacktoberfest-accepted, hacktoberfest

#24 please merge
  01. Cpp Books/DS(Karumanchi).pdf
  C (Dennis Ritchie).pdf
Labels: hacktoberfest-accepted, hacktoberfest

#26 Added Interview Preparation Book
  Interview Preparation/150 Interview Questions.pdf
  Interview Preparation/README.md
Labels: hacktoberfest-accepted, hacktoberfest

#28 React Interview questions for begineers
  Interview Preparation/React For Begineers.pdf
Labels: hacktoberfest-accepted, hacktoberfest

#27 Aptitude Questions
  Aptitude/Complete Quantitative Aptitude Questions Complete Quantitative Aptitude Questions for SBI,IBPS ... ( PDFDrive ).pdf
Labels: hacktoberfest-accepted, hacktoberfest

#29 Automate the boring stuff with python
  08. python books/AutomateTheBoringStuffWithPython.md
  08. python books/readme.md
Labels: hacktoberfest-accepted, hacktoberfest

#33 Add files via upload
  02. Dsa books/cpp_tutorial.pdf
Labels: hacktoberfest-accepted, hacktoberfest

#34 Add files via upload
  02. Dsa books/dsa.pdf
Labels: hacktoberfest-accepted, hacktoberfest

#36 Added the must have book for Competitive coding.
  04. Programming Books/Competitive_Programmers_Handbook.pdf
Labels: hacktoberfest-accepted, hacktoberfest

#37 merg3
  CSE book.pdf
Labels: hacktoberfest-accepted, hacktoberfest

#38 merg4
  03. Web development books/NodeJSNotesForProfessionals.pdf
Labels: hacktoberfest-accepted, hacktoberfest

#43 Heart Disease Prediction Research Paper
  ML Resource/Heart Disease Prediction ResearchPaper.pdf
Labels: hacktoberfest-accepted, hacktoberfest

#44 Add files via upload
  06. Android dev books/thinkpython2 (1).pdf
Labels: hacktoberfest-accepted, hacktoberfest

#45 Add files via upload
  02. Dsa books/cprogrammingquestion (1).pdf
Labels: help wanted, hacktoberfest-accepted, hacktoberfest

#47 Add files via upload
  04. Programming Books/✅ Database Management System (DBMS) And SQL Notes ✅.pdf
Labels: hacktoberfest-accepted, hacktoberfest

#48 Add files via upload
  06. Android dev books/69517364_sOffline_16840_JD29983.pdf
Labels: hacktoberfest-accepted, hacktoberfest

#49 Add files via upload
  05. Hacking Books/Basics of Business Communication.pdf
Labels: hacktoberfest-accepted, hacktoberfest

#50 Add files via upload
  05. Hacking Books/thinkpython2 (1).pdf
Labels: hacktoberfest-accepted, hacktoberfest

#51 Add files via upload
  03. Web development books/cprogrammingquestion (1).pdf
Labels: hacktoberfest-accepted, hacktoberfest

#52 Add files via upload
  03. Web development books/UNIT2 Complete (1).pdf
Labels: hacktoberfest-accepted, hacktoberfest

#53 Add files via upload
  07.  Java books/Assignment Frontend Intern.pdf
Labels: hacktoberfest-accepted, hacktoberfest

#55 Add files via upload
  03. Web development books/17. Permutations - Notes_watermark.pdf
  07.  Java books/1 pager soft dev backend.pdf
  50ca8d7933c8a0ba224daba564321afb18fd313e-1647236068478.pdf
  ML Resource/50ca8d7933c8a0ba224daba564321afb18fd313e-1647236068478.pdf
Labels: hacktoberfest-accepted, hacktoberfest

#57 Added new java book
  07.  Java books/Java Programming For Beginners.pdf
Labels: hacktoberfest-accepted, hacktoberfest

#58 khushboo
  01. Cpp Books/17. Permutations - Notes_watermark.pdf
  05. Hacking Books/1 pager soft dev backend.pdf
Labels: hacktoberfest

#59 Add files via upload
  Interview Preparation/17. Permutations - Notes_watermark.pdf
Labels: hacktoberfest-accepted, hacktoberfest

#60 Add files via upload
  05. Hacking Books/68117321_sOffline_16840_Intern_FullStack_Assignment (1).pdf
Labels: hacktoberfest-accepted, hacktoberfest

#61 Add files via upload
  06. Android dev books/Academic Task 2-Presentation.pdf
Labels: hacktoberfest-accepted, hacktoberfest

#64 Added Java Interview Questions
  Interview Preparation/Java Interview Questions.pdf
  Interview Preparation/SQL Interview Questions.pdf
Labels: hacktoberfest-accepted, hacktoberfest

#65 Added AutoEncoder
  ML Resource/AutoEncoder.pptx
Labels: hacktoberfest-accepted, hacktoberfest

#69 Added JavaScript_Interview_Questions
  Interview Preparation/JavaScript_Interview_Questions.pdf
Labels: hacktoberfest-accepted, hacktoberfest

#71 Add files via upload
  Information Security/thinkpython2 (1).pdf
Labels: hacktoberfest-accepted, hacktoberfest

#72 Add files via upload
  07.  Java books/Software Dev Assignment.pdf
Labels: hacktoberfest-accepted, hacktoberfest

#73 Add files via upload
  07.  Java books/cprogrammingquestion (1).pdf
Labels: hacktoberfest-accepted, hacktoberfest

#75 Add files via upload
  02. Dsa books/KotlinNotesForProfessionals.pdf
Labels: hacktoberfest-accepted, hacktoberfest

#76 Added cracking the coding Interview
  Interview Preparation/Cracking The Coding Interview.pdf
Labels: hacktoberfest-accepted, hacktoberfest

#77 Added
  Interview Preparation/Reactjs_Interview_Questions.pdf
  Interview Preparation/android interview questions.pdf
  Interview Preparation/node-js-interview-questions.pdf
  Interview Preparation/python_interview_questions.pdf
  Interview Preparation/selenium_interview_question.pdf
Labels: hacktoberfest-accepted, hacktoberfest

#78 Added Hr interview question
  Interview Preparation/Hr interview question.pdf
Labels: hacktoberfest-accepted, hacktoberfest

#79 Added php-interview-questions-answers
  Interview Preparation/php-interview-questions-answers.pdf
Labels: hacktoberfest-accepted, hacktoberfest

#80 added linux-interview-questions-answers
  Interview Preparation/linux-interview-questions-answers.pdf
Labels: hacktoberfest-accepted, hacktoberfest

#81 Add files via upload
  Aptitude/cprogrammingquestion (1).pdf
Labels: hacktoberfest-accepted, hacktoberfest

#82 Add files via upload
  Information Security/KotlinNotesForProfessionals.pdf
Labels: hacktoberfest-accepted, hacktoberfest

#83 Add files via upload
  Interview Preparation/thinkpython2 (1).pdf
Labels: hacktoberfest-accepted, hacktoberfest

#84 Add files via upload
  ML Resource/Basics of Business Communication.pdf
Labels: hacktoberfest-accepted, hacktoberfest
